### ISSUE TITLE
Split fa_bot.py from one monolithic file

### ISSUE THREAD

**Issue by mdennehy** [darkChozo/FAbot#12]
The bot commands need to come out to a seperate file, as do the gameserver and event manager classes and the main() stuff needs to be converted into an FABot class and split out as well and the "main" executable becomes a far simpler main() that just kicks everything off.

**Comment by Boberro** [comment]
I can look into it. Don't have any faith in my work project any more (or at least today I don't) and I need to look busy :)

**Comment by Boberro** [comment]
https://github.com/darkChozo/FAbot/pull/19
