### ISSUE TITLE
Polling of arma server during session time

### ISSUE THREAD

**Issue by mdennehy** [darkChozo/FAbot#14]
We need FABot to announce when the ARMA server goes into slotting mode during our sessions; this means that during the period from 1920h GMT to ~0000h GMT (or between a host using a "!session starting" and a "!session finished" command), the bot has to poll the server regularly (every 30-60 seconds?) and catch transitions into the slotting state and announce those in #general on the discord server.

**Comment by darkChozo** [comment]
#38
